name: do_auth
description: Library of Authentication.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.6
  bloc: ^6.1.0
  formz: ^0.3.2
  equatable: ^1.2.5
  dio: ^3.0.10
  retrofit: ^1.3.4+1
  meta: ^1.2.3
  global_configuration: ^1.6.0
  json_annotation: ^3.1.0
  logger: ^0.9.4
  do_api:
    path: ../do_api
  do_storage:
    path: ../do_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  build_runner: ^1.10.4
  retrofit_generator: ^1.4.0
