name: do_dart
description: Dongkap | Mobile Application with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  smooth_star_rating: ^1.1.1
  intl: ^0.16.0
  flutter_svg: ^0.19.1
  flutter_launcher_icons: ^0.8.1
  do_core:
    path: packages/do_core
  do_storage:
    path: packages/do_storage
  do_api:
    path: packages/do_api
  do_theme:
    path: packages/do_theme
  do_auth:
    path: packages/do_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.3
  json_serializable: ^3.5.0
  build_runner: ^1.10.4
  retrofit_generator: ^1.4.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#FFF"
  adaptive_icon_padding: true

flutter:
  uses-material-design: true
  assets:
    - assets/app/
    - assets/avatars/
    - assets/eva_icons/fill/svg/
    - assets/eva_icons/outline/svg/
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
