name: do_core
description: Library core logic.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.3
  global_configuration: ^1.6.0
  json_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  build_runner: ^1.10.4
