name: Dongkap Analyzer

on:
  push:
    branches: [ master ]

jobs:
  package-analysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: do_dart/
